[pytest]
# Parametros que definen todos los archivos de prueba (que comiencen con "test_")
python_files = test_*.py
python_classes = Test*
python_functions = test_*
addopts = -v --html=report.html --self-contained-html